server:
  port: ${PORT:8082}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_grades
    username: postgres
    password: developer
    hikari:
      maximum-pool-size: 5
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false